### ISSUE TITLE
QSM 

### ISSUE THREAD

**Issue by Saadi4469** [Antguz/rTLS#23]
Hello,

First of all kudos on the nice package; does your package help in computing quantitative structural model (QSM) of trees? I am looking for a way to compute QSM in R.

Cheers,

**Comment by Antguz** [comment]
Hi,

Thanks for your comment. Unfortunately we do not support QSM yet. The history of QSM has a lot of pitfalls when you compare methods, thus it is not clear which is the proper way in order to invest time for its implementation. Currently there is a lot of software out there that allow to fit QSMs (with certain differences). If you are interested in open software I recommend you  AdTree [1] or 3DForest [2]. 

This is not an issue, thus I will close it.

 [1] https://github.com/tudelft3d/adtree
 [2] https://www.3dforest.eu/
